CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS STUDENT(
    STUDENT_ID uuid NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR(10) NOT NULL,
    LASTNAME VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    ADMISSION_AT DATE NOT NULL
);